### ISSUE TITLE
Impossible d'utiliser le module

### ISSUE THREAD

**Issue by ney-web** [ZyXProFR/whentocop-api#1]
Lorsque je veux lancer mon script cette erreur est affiché :
![image](https://user-images.githubusercontent.com/83525383/197420654-e691969f-328b-4655-bdfa-3556caedeffd.png)

**Comment by ZyXProFR** [comment]
Il faut être dans une fonction asynchrone pour utiliser `await`, sinon il faut utiliser `.then()`.

**Comment by ney-web** [comment]
> Il faut être dans une fonction asynchrone pour utiliser `await`, sinon il faut utiliser `.then()`.

tu aurais pas le code le repo d'un bot qui utilise ce module ?

**Comment by ZyXProFR** [comment]
Non désolé, mais c'est expliqué ici : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by ney-web** [comment]
> Non désolé, mais c'est expliqué ici : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/async_function

merci j'ai réussi a utiliser, mais le soucis c'est que j'arrive pas utiliser les données json récupérer

**Comment by ney-web** [comment]
ducoup ?

**Comment by ZyXProFR** [comment]
Pour la manipulation des données JSON tu peux trouver les informations ici : https://developer.mozilla.org/fr/docs/Learn/JavaScript/Objects/JSON

Si tu es sur VSCode tu es censé avoir l'auto-complétion pour les propriétés, par exemple pour le nom du modèle `.model_name`, etc.

**Comment by ney-web** [comment]
ce serait pas possible d'avoir ton # discord pour en discuter ?

**Comment by ZyXProFR** [comment]
Je préfère rester sur Github pour les demandes d’aide, ça servira pour les autres personnes qui pourrait avoir les mêmes soucis.Le 30 oct. 2022 à 13:15, ye ***@***.***> a écrit :﻿
ce serait pas possible d'avoir ton # discord pour en discuter ?

**Comment by ney-web** [comment]
D'accord mais je rencontre un nouveau problème lors du fetch.
Désormais cela ne m'affiche uniquement ceci : `Promise { [] }`

**Comment by ney-web** [comment]
Je n'arrive vraiment plus à utiliser ce module :(

**Comment by ZyXProFR** [comment]
C'est que tu n'as pas utilisé `await` ou `.then()` selon le type de fonction dans laquelle tu exécute le code.

Si tu es dans une fonction asynchrone tu peux utiliser `await` comme dans l'exemple du `README.md` sinon il faut utiliser `.then` sur la méthode `fetchDrops()`

**Comment by ZyXProFR** [comment]
C'est que tu n'as pas utilisé await ou .then() selon le type de fonction dans laquelle tu exécute le code.

Si tu es dans une fonction asynchrone tu peux utiliser await comme dans l'exemple du README.md sinon il faut utiliser .then sur la méthode fetchDrops().

**Comment by ZyXProFR** [comment]
C'est que tu n'as pas utilisé await ou `.then()` selon le type de fonction dans laquelle tu exécute le code.

Si tu es dans une fonction asynchrone tu peux utiliser `await` comme dans l'exemple du `README.md` sinon il faut utiliser `.then` sur la méthode `fetchDrops()`.

Exemple : `fetchDrops(new Date()).then((drops) => console.log(drops));`

**Comment by ney-web** [comment]
Ducoup même en utilsant `.then()` toujours le même soucis. Du moins ce n'est plus `Promise { [] }` qui s'affiche dans la console mais `[]`

**Comment by ZyXProFR** [comment]
C'est qu'il n'y a pas de résultat pour la date que tu as mis.

**Comment by ney-web** [comment]
Pourtant quand je fais la requête http manuellement il y a bien des résultat pour cette date, je ne comprends pas

**Comment by ZyXProFR** [comment]
J'ai regardé et il n'y avait aucun drop le dimanche 30, donc si tu avais juste laissé la date par défaut, il n'y avait aucun résultat. Mets une date où tu es sûr qu'il y a un drop, en mettant le 31 par exemple j'ai des résultats.
